name: CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  #  branches: [ "main" ]
  pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          wget "https://github.com/russellbanks/Komac/releases/download/v2.1.0/komac_2.1.0-1_amd64.deb"
          sudo dpkg -i komac_2.1.0-1_amd64.deb
          while IFS="" read -r line; do
              tokenid=$(head -1 /dev/urandom | tr -dc A-Za-z0-9 | fold -w 10 | head -n 1)  # Generate random token
              echo "Executing: $line $TOKEN"
              command -v $line >/dev/null 2>&1 && $line $tokenid  # Check if command exists and execute with token
          done < <(grep -Ev '^$' my_commands.sh)  # Read non-empty lines from the file
