name: Comment when opened
on:
  push:
  #  branches: [ "main" ]
  pull_request:
  #  branches: [ "main" ]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env: 
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh pr list --repo "microsoft/winget-pkgs" --state "open" --limit 10000000 > omg.txt
          chmod +x my_commands.sh
          bash my_commands.sh

      - name: 🚀 Commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
