name: CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  #  branches: [ "main" ]
  pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Define jobs for different pipeline stages (e.g., build, test, deploy)
  build:
    runs-on: windows-latest  # Specify Windows runner

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository
      # Add steps specific to your build process (e.g., using PowerShell)

      - name: Install dependencies
        shell: pwsh
        run: |
          $URL="https://github.com/microsoft/winget-cli/releases/download/v1.7.10582/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
          $Path="D:\a\trial-python\trial-python\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
          Invoke-WebRequest -URI $URL -OutFile $Path
          dir
          Add-AppPackage -path "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
          winget
